# Generated by Django 5.0.1 on 2024-01-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_level_chart', models.ImageField(upload_to='admin_data/salary_level/%Y/%m/%d', verbose_name='График уровня зарплаты по городам')),
                ('vacancy_fraction_chart', models.ImageField(upload_to='admin_data/vacancy_fraction/%Y/%m/%d', verbose_name='График доли вакансий по городам')),
                ('statistics_table', models.TextField(verbose_name='Таблица статистики')),
            ],
        ),
        migrations.CreateModel(
            name='JobDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_level_chart', models.ImageField(upload_to='admin_data/%Y/%m/%d', verbose_name='График уровень зарплат по годам')),
                ('vacancy_count_chart', models.ImageField(upload_to='admin_data/%Y/%m/%d', verbose_name='График количество вакансий по годам')),
                ('data_table', models.TextField(verbose_name='Таблица')),
            ],
        ),
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, verbose_name='Текст описания')),
                ('photo', models.ImageField(upload_to='admin_data/%Y/%m/%d', verbose_name='Фото профессии')),
            ],
        ),
        migrations.CreateModel(
            name='Navigations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_title', models.TextField(max_length=100, verbose_name='Заголовок вакансии')),
                ('logo_image', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='Логотип')),
                ('first_menu_item', models.TextField(max_length=25, verbose_name='Первый пункт меню')),
                ('second_menu_item', models.TextField(max_length=25, verbose_name='Второй пункт меню')),
                ('third_menu_item', models.TextField(max_length=25, verbose_name='Третий пункт меню')),
                ('fourth_menu_item', models.TextField(max_length=25, verbose_name='Четвертый пункт меню')),
                ('fifth_menu_item', models.TextField(max_length=25, verbose_name='Пятый пункт меню')),
                ('author_name', models.TextField(max_length=50, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='RecentVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок работы')),
                ('content_to_parse', models.TextField(max_length=15, verbose_name='Текст вакансии для парсинга')),
                ('date', models.DateField(blank=True, verbose_name='Дата парсинга')),
            ],
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_table', models.TextField(max_length=30, verbose_name='Название таблицы')),
                ('table', models.TextField(verbose_name='Таблица')),
                ('graph', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График по скиллам')),
            ],
        ),
    ]
