# Generated by Django 5.0.1 on 2024-01-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_level_chart', models.ImageField(upload_to='admin_data/salary_level/%Y/%m/%d', verbose_name='График уровня зарплаты по городам')),
                ('vacancy_fraction_chart', models.ImageField(upload_to='admin_data/vacancy_fraction/%Y/%m/%d', verbose_name='График доли вакансий по городам')),
                ('statistics_table', models.TextField(verbose_name='Таблица статистики')),
            ],
        ),
        migrations.CreateModel(
            name='JobDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_level_chart', models.ImageField(upload_to='admin_data/%Y/%m/%d', verbose_name='График уровень зарплат по годам')),
                ('vacancy_count_chart', models.ImageField(upload_to='admin_data/%Y/%m/%d', verbose_name='График количество вакансий по годам')),
                ('data_table', models.TextField(verbose_name='Таблица')),
            ],
        ),
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, verbose_name='Текст описания')),
                ('photo', models.ImageField(upload_to='admin_data/%Y/%m/%d', verbose_name='Фото профессии')),
            ],
        ),
    ]
