# Generated by Django 5.0.1 on 2024-01-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_vacancy', '0002_skillset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_title', models.TextField(max_length=100, verbose_name='Заголовок вакансии')),
                ('logo_image', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='Логотип')),
                ('first_menu_item', models.TextField(max_length=25, verbose_name='Первый пункт меню')),
                ('second_menu_item', models.TextField(max_length=25, verbose_name='Второй пункт меню')),
                ('third_menu_item', models.TextField(max_length=25, verbose_name='Третий пункт меню')),
                ('fourth_menu_item', models.TextField(max_length=25, verbose_name='Четвертый пункт меню')),
                ('fifth_menu_item', models.TextField(max_length=25, verbose_name='Пятый пункт меню')),
                ('author_name', models.TextField(max_length=50, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='RecentVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок работы')),
                ('content_to_parse', models.TextField(max_length=15, verbose_name='Текст вакансии для парсинга')),
            ],
        ),
    ]
